
name = "slm-pcre"
version = "0.0.2"

[dependencies]

[dependencies.pcre]
pkg="pcre"
version="8.45"
type="conan"
options.build_pcre_16="True"
options.build_pcre_32="True"
options.build_pcre_8="True"
options.build_pcrecpp="False"
options.build_pcregrep="True"
options.shared="False"
options.with_bzip2="True"
options.with_jit="False"
options.with_stack_for_recursion="True"
options.with_unicode_properties="True"
options.with_utf="True"
options.with_zlib="True"
options.linux.fPIC="True"
options.macos.fPIC="True"
